= Android set-up required for Ost React Native SDK
:doctype: book

== 1. Linking the Ost React Native SDK

=== Automatic Linking

[source,bash]
----
react-native link @ostdotcom/ost-wallet-sdk-react-native
----

=== Manual Linking

. Open `+./android/app/src/main/java/[...]/MainApplication.java+`
. Add `import com.ostwalletrnsdk.OstWalletRnSdkPackage;` to the imports at the top of the file.
. Add `new OstWalletRnSdkPackage()` to the list returned by the `getPackages()` method
. Append the following lines to `./android/settings.gradle`: `include ':ost-wallet-sdk-react-native' project(':ost-wallet-sdk-react-native').projectDir = new File(rootProject.projectDir, 	'../node_modules/ost-wallet-sdk-react-native/android')`
. Insert the following lines inside the dependencies block in `./android/app/build.gradle`: compile project(':ost-wallet-sdk-react-native')

== 2. Changing `minSdkVersion` in './android/build.gradle' file

Change the `minSdkVersion` to 22 in `android/build.gradle`

[source,json]
----
android {
    defaultConfig {
        minSdkVersion 22
        ...
        ...
        ...
    }
}
----

== 3. Create SDK configuration file

Create file `./android/app/src/main/assets/ost-mobilesdk.json` with application specific configurations using the json below as an example

[source,json]
----
{
  "BLOCK_GENERATION_TIME": 3,
  "PIN_MAX_RETRY_COUNT": 3,
  "REQUEST_TIMEOUT_DURATION": 60,
  "SESSION_BUFFER_TIME": 3600,
  "PRICE_POINT_CURRENCY_SYMBOL": "USD",
  "USE_SEED_PASSWORD": false
}
----

. BlockGenerationTime: The time in seconds it takes to mine a block on auxiliary chain.
. PricePointTokenSymbol: This is the symbol of base currency. So its value will be OST.
. PricePointCurrencySymbol: It is the symbol of quote currency used in price conversion.
. RequestTimeoutDuration: Request timeout in seconds for https calls made by ostWalletSdk.
. PinMaxRetryCount: Maximum retry count to get the wallet Pin from user.
. SessionBufferTime: Buffer expiration time for session keys in seconds.
Default value is 3600 seconds.
. UseSeedPassword: The seed password is salt to PBKDF2 used to generate seed from the mnemonic.
When UseSeedPassword set to `true`, different deterministic salts are used for different keys.

*NOTE: These configurations are MANDATORY for successful operation.
Failing to set them will significantly impact usage.*

= Debug builds with Android 9 (API level 28)

Starting with Android 9 (API level 28), https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted[cleartext support] is disabled by default.

On the other hand, Ost Wallet Android Sdk leverages on *Public Key Pinning* to ensure the authenticity of a Ost Platform server's public key used in TLS sessions using https://github.com/datatheorem/TrustKit-Android[TrustKit].
As TrustKit can only be inititialized with application's https://developer.android.com/training/articles/security-config[network security configuration], sdk initialization fails.

To work-around this issues, application needs to have TrustKit as a dependency and initialize it.

Please refer to https://github.com/ostdotcom/ost-wallet-sdk-android/blob/develop/documentation/TrustKitPublickeyPinning.md[Public Key Pinning Using TrustKit] documentation.